services:
  rcon-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev     
    container_name: rcon-dev

    ports:
      - "80:80"                   

    env_file:
      - .env                         
    volumes:
      - .env:/app/.env:ro              